#+TITLE: Kwdcmd: Keywords for Cmdliner CLI's
#+SUBTITLE: A lightweight and partial porcelain around [[https://erratique.ch/software/cmdliner} ][Cmdliner]].

Cmdliner is a powerful library for composable command line interfaces, but it is
relatively low level.  Most users have to look up the documentation every time
they want to use the combinators correctly.

This thin wrapper library is best thought of as an executable cookbook for
common Cmdliner usage patterns, or as programmatic documentation encoded in the
type level.

The recipes are divided between module namespaces and the functions are
documented with named arguments.

This library is in early stages, and is growing as the need for patterns arises.

* Ideals

- Remain true to the Cmdliners compositional principles (no side-effecting
  shortcuts or other chicanery).
- Unfamiliar users should be able to write their CLIs within 10 minutes of
  reading the docs.
- Familiar users should find everything they need to know to write clean,
  expressive CLIS's self-documented in the type signatures of the library's
  modules and functions.

Please [[https://github.com/shonfeder/kwdcmd/issues/new ][open an issue]] or [[https://github.com/shonfeder/kwdcmd/blob/master/CONTRIBUTING.org][add a feature]] if you think the library could be improved
to better meet these ideals.
