name: release

on:
  push:
    tags:
      - "*.*.*"

jobs:
  release:
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
          # - macos-latest
          # - windows-latest
        ocaml-version:
          - 4.11.0
            # - 4.10.1
            # - 4.09.1
            # - 4.08.1

    runs-on: ${{ matrix.os }}

    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          depth: 0

      - name: Cache opam repository
        uses: actions/cache@v2
        with:
          path: ~/.opam
          key: ${{ runner.os }}-${{ hashFiles('*.opam') }}-${{ matrix.ocaml-version }}

      - name: Use OCaml ${{ matrix.ocaml-version }}
        uses: actions-ml/setup-ocaml@master
        with:
          ocaml-version: ${{ matrix.ocaml-version }}

      - name: Install deps
        run: opam install . --deps-only --with-doc --with-test

      - name: Build release binary
        run: |
          opam exec -- dune test
          opam exec -- dune build --profile release

      - name: Cut release
        run: |
          set -x

          git config --global user.name "$GITHUB_ACTOR"
          git config --global user.email "github@actions.ci"
          version=$(git describe --tags --abbrev=0)

          opam install dune-release
          opam exec -- dune-release distrib --tag $version

          hub release create $version \
            -a "_build/kwdcmd-${version}.tbz" \
            -m "$version" \
            -m "$(git tag -l --format='%(contents)' "$version" | tail -n +3)"
